### ISSUE TITLE
MMM-ModuleToggleButton  does not work with MMM-RemoteCompliments

### ISSUE THREAD

**Issue by ageens** [balassy/MMM-ModuleToggleButton#1]
It seem to me that ToggleButton does not work for "MMM-RemoteCompliments" 
Wat does i need to do to get this working?

By the way, thks for designing this ToggleButton.

**Comment by balassy** [comment]
Hello @ageens, could you please send more information about what do you mean by "does not work" and also include your configuration?
Thanks.

**Comment by balassy** [comment]
I close this issue because of inactivity and lack of details, but feel free to reopen it if you have more information.
