### ISSUE TITLE
No signal with GPIO

### ISSUE THREAD

**Issue by nee0** [balassy/MMM-ModuleToggleButton#2]
I have installed MMM-ModuleToggleButton.
The module hides the specific modules as wanted.

I have activated the GPIO in Raspberry pi menu.
Iam using pin 20 (GND) and 22 (GPIO 6) to my momentary switch.
Using Raspbeery pi 2 model B.

No response when i press the switch. Anyone have any idea?

This is the config iam using. 
```
{	
	      module: 'MMM-ModuleToggleButton',
	      config: {
		buttonGpioPin: 6,
		moduleNames: [
		  'clock',
		  'calendar'
		]
	      }
 },
```

**Comment by balassy** [comment]
Hello @nee0,
There is nothing in the code that would prevent the module to work with your settings, actually I'm using it with the same configuration.
But according to [this page](http://www.raspberry-pi-geek.com/howto/GPIO-Pinout-Rasp-Pi-1-Model-B-Rasp-Pi-2-Model-B) `GPIO 6` is on pin 31, not on 22. 
Could you please double check your wiring?

**Comment by balassy** [comment]
I'm closing this issue because it was not updated for more than 4 years.
