### ISSUE TITLE
err code elifecycle

### ISSUE THREAD

**Issue by larolds** [balassy/MMM-ModuleToggleButton#4]
hello, i'm building a mirror for my wife and i'm trying to install this module. be advised I am extremely green to linux. i'm trying to perform the install and every time i execute the command npm install i get an error i understand i need to either specify the version number or install but i am not sure what to do this point. I have followed the path and direction that it tells me but i cannot figure it out. the error i get is as follows.

> MMM-ModuleToggleButton@1.0.0 postinstall /home/pi/MagicMirror/modules/default/MMM-ModuleToggleButton
> electron-rebuild -e ../../node_modules/electron

An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at /home/pi/MagicMirror/modules/default/MMM-ModuleToggleButton/node_modules/electron-rebuild/lib/src/cli.js:86:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/default/MMM-ModuleToggleButton/node_modules/electron-rebuild/lib/src/cli.js:6:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! MMM-ModuleToggleButton@1.0.0 postinstall: `electron-rebuild -e ../../node_modules/electron`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the MMM-ModuleToggleButton@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-22T03_46_48_568Z-debug.log

Thank you in advanced. i really appreciate any help at all. i love this concept and am excited to get it to work.

**Comment by balassy** [comment]
Hello @larolds and thanks for trying this module!

From the logs I see that you have installed this module to the `modules/default` folder of MagicMirror, which is intended to contain only the built-in modules, not third-party modules, like this. Could you please try to install it into the `modules` (`modules/MMM-ModuleToggleButton`) folder?

**Comment by balassy** [comment]
I'm closing this issue because it was not updated for about 4 years.
